@startuml
title Manchester encoder states

note as N1
  <b>Parameters</b>
    wordSize (<i>integer</i>)
    bitTime (<i>time</i>)
  <b>Inputs</b>
    data[wordSize] (<i>Boolean</i>)
  <b>Events</b>
    clockEdge
    newWord
  <b>Outputs</b>
    output (<i>Boolean</i>)

  <b>Notes:</b>
    - Sends 0's in the Quiescent state.
    - Should be left in the Quiescent
      state for a minimum period before
      the first word is queued to allow
      synchronization.
    - All data words should start with 1.
end note


[*]-->Quiescent

state Quiescent {
    [*]-->HiToggle
    HiToggle: output = HI
    HiToggle->LoToggle: clockEdge
    HiToggle-->HiDataReady: newData
    
    LoToggle: output = LO
    LoToggle->HiToggle: clockEdge
    LoToggle-->LoDataReady: newData

    HiDataReady-->LoDataReady: clockEdge

    LoDataReady-->[*]: clockEdge
}
Quiescent-->StartBitInit

StartBitInit: bitCount = 0

StartBitInit-->StartBitMid: clockEdge

StartBitMid: output = LO
state MidWord <<choice>>
StartBitMid-->MidWord: clockEdge

MidWord-->BitInit: bitCount < wordSize
MidWord-->WordExit: bitCount == wordSize

BitInit: output = !data[bitCount]
BitInit-->MidBit: clockEdge

MidBit: output = !output
MidBit: bitCount += 1
MidBit-->MidWord: clockEdge

WordExit: output = HI
WordExit-->Quiescent

@enduml
